name: drinkingthings
favicon: null
layout_spectrum: 0.60952
typography_spectrum: 0.69601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171813'
    - '#393937'
    - '#8ca4d0'
    - '#607980'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.2925276441965252
purpose: []
